name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t devcontainer .devcontainer

      - name: Run audit
        run: |
          docker run --rm \
            -e CI=true \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            devcontainer \
            sh -c '
              set -e
              npm audit
            '
